dist: xenial

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=2.1,<2.2"
  - DJANGO="django>=2.2,<2.3"
  - DJANGO="django>=3.0,<3.1"
  - DJANGO="django>=3.1,<3.2"

before_install:
  - export DJANGO_SETTINGS_MODULE=demo.demo_classified.project.settings
  - export PYTHONPATH=$HOME/builds/inoks/django-classified
  - export PIP_USE_MIRRORS=true

install:
  - pip install $DJANGO --quiet
  - python setup.py install
  - pip install flake8
  - pip install coverage

before_script:
  - flake8  --ignore=E501,E122

script:
  - coverage run --source='.' quicktest.py django_classified

after_success:
  - coverage report --show-missing
